version: '2'
services:
  image-db:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_DATABASE=card-db
    volumes:
      - ~/data/db/card-db:/data/db
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null # --quiet